### ISSUE TITLE
Data sampling strategy

### ISSUE THREAD

**Issue by azmiara** [nishagandhi/DrowsyDriverDetection#2]
Hello Nisha, Thanks for sharing your work. It's great. I am working on the same topic of Driver drowsiness detection. 
My dataset has 25fps and labeling of drowsy or alert is done in every 2 minutes.I want to stick to a window size of 25.
Which of the below 2 methods is a better way of sampling data??
*  Should I consider the sequential frames from  119sec-120sec for classification ?? OR 
 * Should I consider every 120th frame(every 5th second) for classifying drowsy or alert??

I see that your input has a window size of 26. So where these frames collected sequentially or after regular intervals of time?﻿

**Comment by nishagandhi** [comment]
Hi Azmiara,

Apologies for the late reply.

According to me, the sequential frames from 119-120 should be considered since they will have approx 50 frames sequential data as compared to the second method, where data between every 120 frames will be ignored (which will be crucial for drowsiness detection).

I have collected these frames sequentially. Let me know if I can help in any other way.

Thanks,
Nisha
